### ISSUE TITLE
cannot open the .nii files saved via .write function

### ISSUE THREAD

**Issue by huyang200606** [cosanlab/nltools#323] opened 2019-12-22 10:41 UTC
Dear nltools developers,
    I would like to save a certain ROI from the 'Neurosynth_Parcellation_0.nii.gz' file with the following commands:

mask = Brain_Data(os.path.join(maskdir,'Neurosynth_Parcellation_0.nii.gz')) # 50-region parcellation
mask_all = expand_mask(mask)
bTPJ_mask = mask_all[5]
bTPJ_mask.plot() # which looks good
bTPJ_mask.write(os.path.join(maskdir,'bTPJ_mask.nii.gz'))

   However, I failed to open the bTPJ_mask.nii file with spm, mricon, or xjview (but I can successfully open Neurosynth_Parcellation_0.nii with these softwares). Could someone help me to figure it out? 

   Thanks for your help and have a nice day!

Best,
Yang

**Comment by ejolly** [comment] 2020-01-21 15:17
Hi Yang,

That is unusual. Can you upload `bTPJ_mask.nii` here along with `Neurosynth_Parcellation_0.nii.gz` so I can take a look? Also what specific error are you receiving when you try to open the file in spm/mricon/xjview? It looks like you're saving out a zipped file `.nii.gz` as oppose to an unzipped one `.nii`. Have you tried saving and opening an unzipped file?

**Comment by ejolly** [comment] 2020-03-09 17:07
Closing this as we haven't been able to reproduce it. Feel free to reopen with some more details about the problem

**Closed by ejolly** 2020-03-09 17:07 UTC
